version: '3.8'
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    user: '0'  # If you are running as root then set it to 0 else find the right id with the id -u command
    environment:
      - GF_SERVER_DOMAIN=grafana.leeu.me
      - GF_LOG_LEVEL=debug
      - "GF_LOG_MODE=console file"
    volumes:
      - './data:/var/lib/grafana'
    network_mode: host

  loki:
    image: grafana/loki:main
    command: -config.file=/etc/loki/local-config.yaml
    network_mode: host

  promtail:
    image: grafana/promtail:main
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    network_mode: host
