version: '3.8'
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    # if you are running as root then set it to 0
    # else find the right id with the id -u command
    user: '0'
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - GF_SERVER_DOMAIN=grafana.leeu.me
      - GF_LOG_LEVEL=debug
      - "GF_LOG_MODE=console file"
    # adding the mount volume point which we create earlier
    volumes:
      - './data:/var/lib/grafana'
    networks:
      - loki
  loki:
    image: grafana/loki:main
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:main
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

networks:
    loki:
      name: loki
